name: Build and Release JAR

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Derive version from tag
        id: vars
        shell: bash
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          # Strip leading 'v' if present, e.g. v1.2.3 -> 1.2.3
          RELEASE_VERSION="${TAG_NAME#v}"
          echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          echo "Release version: ${RELEASE_VERSION}"

      - name: Build shaded JAR
        run: |
          ./gradlew --no-daemon clean assemble -PreleaseVersion="${{ steps.vars.outputs.release_version }}"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jars-${{ steps.vars.outputs.release_version }}
          path: |
            build/libs/*${{ steps.vars.outputs.release_version }}*.jar
          if-no-files-found: error

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            build/libs/*${{ steps.vars.outputs.release_version }}*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
